name: "Build & Release"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      ANDROID_ARCH: x86_64
      ANDROID_TARGET: google_apis_playstore
      API_LEVEL: 33
      ANDROID_BUILD_TOOLS_VERSION: 33.0.2
      EMULATOR_NAME: nexus
      EMULATOR_TIMEOUT: 350

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Auto format the dart code
        run: dart format .

      - name: Verify the dart code is formatted
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze the dart code
        run: flutter analyze --fatal-warnings

      # Install Android SDK tools
      - name: Install Android SDK
        run: |
          brew install --cask android-sdk
          echo "export ANDROID_HOME=/usr/local/share/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          curl -s https://dl.google.com/android/repository/commandlinetools-mac-11076708_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm cmdline-tools.zip

      # Accept licenses & install required SDK components
      - name: Install SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "system-images;android-33;google_apis_playstore;x86_64" \
            "emulator"

      # Start emulator using the official action
      - name: Run Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis_playstore
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect
          script: ./gradlew connectedCheck

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}