name: Flutter App on Emulator

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 300
      ANDROID_API_LEVEL: 30
      ANDROID_TARGET: google_apis
      ANDROID_ARCH: x86_64
      ANDROID_PROFILE: Nexus 6

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Run Flutter Lint analyze
        run: flutter analyze

      - name: Run Flutter tests
        run: flutter test

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.ANDROID_API_LEVEL }}

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Flutter app on Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          target: ${{ env.ANDROID_TARGET }}
          arch: ${{ env.ANDROID_ARCH }}
          profile: ${{ env.ANDROID_PROFILE }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            echo "=== Emulator started successfully ==="
            adb devices
            
            echo "=== Building Flutter APK ==="
            flutter build apk --debug
            
            echo "=== Checking build outputs ==="
            ls -la build/app/outputs/
            ls -la build/app/outputs/flutter-apk/ || echo "flutter-apk directory not found"
            ls -la build/app/outputs/apk/ || echo "apk directory not found"
            
            echo "=== Installing Flutter app ==="
            # Try different APK install methods
            adb install -r build/app/outputs/flutter-apk/app-debug.apk || adb install -r build/app/outputs/apk/debug/app-debug.apk || flutter install --debug
            
            echo "=== Verifying app installation ==="
            adb shell pm list packages | grep -i flutter || echo "Flutter app package not found"
            
            echo "=== Taking screenshot ==="
            adb exec-out screencap -p > screenshot.png
            
            echo "=== Flutter app installation completed ==="

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/apk/debug/*.apk
          retention-days: 7

      - name: Upload screenshot artifact (optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: emulator-screenshot
          path: screenshot.png
          retention-days: 7
