name: "Build & Release"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # -------------------------
  # Android integration tests
  # -------------------------
  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Run Integration Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          profile: pixel_5
          emulator-options: -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            flutter drive \
              --driver=test_driver/integration_test.dart \
              --target=integration_test/app_test.dart

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/apk/release/*.apk

  # -------------------------
  # iOS build
  # -------------------------
  ios-build:
    runs-on: macos-latest
    needs: android-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload  

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa
